import type { KnowledgeConnector, KnowledgeEntry, ContributionResult } from './types.js';
import yaml from 'js-yaml';

export class GitHubPrivateConnector implements KnowledgeConnector {
  readonly name = 'github-private';
  private token: string;
  private repo: string;
  private branch: string;

  constructor() {
    this.token = process.env.FLUENTLY_GITHUB_TOKEN ?? '';
    this.repo = process.env.FLUENTLY_GITHUB_REPO ?? '';
    this.branch = process.env.FLUENTLY_GITHUB_BRANCH ?? 'main';
    if (!this.repo) throw new Error('FLUENTLY_GITHUB_REPO is required for github-private connector');
  }

  private get headers(): Record<string, string> {
    const h: Record<string, string> = { 'Accept': 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28' };
    if (this.token) h['Authorization'] = `Bearer ${this.token}`;
    return h;
  }

  async load(): Promise<KnowledgeEntry[]> {
    const res = await fetch(
      `https://api.github.com/repos/${this.repo}/contents/knowledge/index.json?ref=${this.branch}`,
      { headers: this.headers }
    );
    if (!res.ok) throw new Error(`GitHub API error ${res.status}: ${await res.text()}`);
    const file = await res.json() as { content: string };
    const content = Buffer.from(file.content, 'base64').toString('utf8');
    const data = JSON.parse(content) as { entries: KnowledgeEntry[] };
    return data.entries;
  }

  async contribute(cycle: unknown): Promise<ContributionResult> {
    if (!this.token) {
      return {
        success: false,
        message: 'FLUENTLY_GITHUB_TOKEN is required to contribute to a private repository. Set the env var and restart.',
      };
    }

    const entry = cycle as any;
    const yamlStr = yaml.dump(cycle);
    const filename = `${entry.domain}-${entry.id}.yaml`;
    const newBranch = `fluently/add-${entry.id}-${Date.now()}`;

    // Get base branch SHA
    const branchRes = await fetch(
      `https://api.github.com/repos/${this.repo}/git/ref/heads/${this.branch}`,
      { headers: this.headers }
    );
    if (!branchRes.ok) return { success: false, message: `Could not get branch SHA: ${branchRes.status}` };
    const branchData = await branchRes.json() as { object: { sha: string } };
    const sha = branchData.object.sha;

    // Create new branch
    await fetch(`https://api.github.com/repos/${this.repo}/git/refs`, {
      method: 'POST',
      headers: { ...this.headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({ ref: `refs/heads/${newBranch}`, sha }),
    });

    // Create file
    const fileRes = await fetch(
      `https://api.github.com/repos/${this.repo}/contents/knowledge/${filename}`,
      {
        method: 'PUT',
        headers: { ...this.headers, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: `feat(knowledge): add ${entry.title}`,
          content: Buffer.from(yamlStr).toString('base64'),
          branch: newBranch,
        }),
      }
    );
    if (!fileRes.ok) return { success: false, message: `Could not create file: ${fileRes.status}` };

    // Open PR
    const prRes = await fetch(`https://api.github.com/repos/${this.repo}/pulls`, {
      method: 'POST',
      headers: { ...this.headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: `feat(knowledge): add ${entry.title}`,
        head: newBranch,
        base: this.branch,
        body: `## New Fluently 4D Cycle\n\n**Title:** ${entry.title}\n**Domain:** ${entry.domain}\n**Contributor:** ${entry.contributor}\n\nGenerated by Fluently MCP server.`,
      }),
    });

    if (!prRes.ok) return { success: false, message: `Could not create PR: ${prRes.status}` };
    const pr = await prRes.json() as { html_url: string; number: number };

    return {
      success: true,
      message: `PR #${pr.number} opened successfully.`,
      url: pr.html_url,
      yaml: yamlStr,
    };
  }
}
